package models

type Country struct {
	Name       string
	Alpha2Code string
}

func (a Country) GetAllCountries() []Country {
	return []Country{

		{Name: "Albania", Alpha2Code: "AL"},
		{Name: "Afghanistan", Alpha2Code: "AF"},
		{Name: "Algeria", Alpha2Code: "DZ"},
		{Name: "Andorra", Alpha2Code: "AD"},
		{Name: "American Samoa", Alpha2Code: "AS"},
		{Name: "Anguilla", Alpha2Code: "AI"},
		{Name: "Angola", Alpha2Code: "AO"},
		{Name: "Antarctica", Alpha2Code: "AQ"},
		{Name: "Antigua and Barbuda", Alpha2Code: "AG"},
		{Name: "Argentina", Alpha2Code: "AR"},
		{Name: "Armenia", Alpha2Code: "AM"},
		{Name: "Aruba", Alpha2Code: "AW"},
		{Name: "Australia", Alpha2Code: "AU"},
		{Name: "Austria", Alpha2Code: "AT"},
		{Name: "Azerbaijan", Alpha2Code: "AZ"},
		{Name: "Bahamas", Alpha2Code: "BS"},
		{Name: "Bahrain", Alpha2Code: "BH"},
		{Name: "Bangladesh", Alpha2Code: "BD"},
		{Name: "Barbados", Alpha2Code: "BB"},
		{Name: "Belarus", Alpha2Code: "BY"},
		{Name: "Belgium", Alpha2Code: "BE"},
		{Name: "Belize", Alpha2Code: "BZ"},
		{Name: "Benin", Alpha2Code: "BJ"},
		{Name: "Bermuda", Alpha2Code: "BM"},
		{Name: "Bhutan", Alpha2Code: "BT"},
		{Name: "Bolivia (Plurinational State of)", Alpha2Code: "BO"},
		{Name: "Bonaire, Sint Eustatius and Saba", Alpha2Code: "BQ"},
		{Name: "Bosnia and Herzegovina", Alpha2Code: "BA"},
		{Name: "Botswana", Alpha2Code: "BW"},
		{Name: "Bouvet Island", Alpha2Code: "BV"},
		{Name: "Brazil", Alpha2Code: "BR"},
		{Name: "British Indian Ocean Territory", Alpha2Code: "IO"},
		{Name: "Brunei Darussalam", Alpha2Code: "BN"},
		{Name: "Bulgaria", Alpha2Code: "BG"},
		{Name: "Burkina Faso", Alpha2Code: "BF"},
		{Name: "Burundi", Alpha2Code: "BI"},
		{Name: "Cabo Verde", Alpha2Code: "CV"},
		{Name: "Cambodia", Alpha2Code: "KH"},
		{Name: "Cameroon", Alpha2Code: "CM"},
		{Name: "Canada", Alpha2Code: "CA"},
		{Name: "Cayman Islands", Alpha2Code: "KY"},
		{Name: "Central African Republic", Alpha2Code: "CF"},
		{Name: "Chad", Alpha2Code: "TD"},
		{Name: "Chile", Alpha2Code: "CL"},
		{Name: "China", Alpha2Code: "CN"},
		{Name: "Christmas Island", Alpha2Code: "CX"},
		{Name: "Cocos (Keeling) Islands", Alpha2Code: "CC"},
		{Name: "Colombia", Alpha2Code: "CO"},
		{Name: "Comoros", Alpha2Code: "KM"},
		{Name: "Congo", Alpha2Code: "CG"},
		{Name: "Congo (Democratic Republic of the)", Alpha2Code: "CD"},
		{Name: "Cook Islands", Alpha2Code: "CK"},
		{Name: "Costa Rica", Alpha2Code: "CR"},
		{Name: "Croatia", Alpha2Code: "HR"},
		{Name: "Cuba", Alpha2Code: "CU"},
		{Name: "Curaçao", Alpha2Code: "CW"},
		{Name: "Cyprus", Alpha2Code: "CY"},
		{Name: "Czech Republic", Alpha2Code: "CZ"},
		{Name: "Côte d'Ivoire", Alpha2Code: "CI"},
		{Name: "Denmark", Alpha2Code: "DK"},
		{Name: "Djibouti", Alpha2Code: "DJ"},
		{Name: "Dominica", Alpha2Code: "DM"},
		{Name: "Dominican Republic", Alpha2Code: "DO"},
		{Name: "Ecuador", Alpha2Code: "EC"},
		{Name: "Egypt", Alpha2Code: "EG"},
		{Name: "El Salvador", Alpha2Code: "SV"},
		{Name: "Equatorial Guinea", Alpha2Code: "GQ"},
		{Name: "Eritrea", Alpha2Code: "ER"},
		{Name: "Estonia", Alpha2Code: "EE"},
		{Name: "Ethiopia", Alpha2Code: "ET"},
		{Name: "Falkland Islands (Malvinas)", Alpha2Code: "FK"},
		{Name: "Faroe Islands", Alpha2Code: "FO"},
		{Name: "Fiji", Alpha2Code: "FJ"},
		{Name: "Finland", Alpha2Code: "FI"},
		{Name: "France", Alpha2Code: "FR"},
		{Name: "French Guiana", Alpha2Code: "GF"},
		{Name: "French Polynesia", Alpha2Code: "PF"},
		{Name: "French Southern Territories", Alpha2Code: "TF"},
		{Name: "Gabon", Alpha2Code: "GA"},
		{Name: "Gambia", Alpha2Code: "GM"},
		{Name: "Georgia", Alpha2Code: "GE"},
		{Name: "Germany", Alpha2Code: "DE"},
		{Name: "Ghana", Alpha2Code: "GH"},
		{Name: "Gibraltar", Alpha2Code: "GI"},
		{Name: "Greece", Alpha2Code: "GR"},
		{Name: "Greenland", Alpha2Code: "GL"},
		{Name: "Grenada", Alpha2Code: "GD"},
		{Name: "Guadeloupe", Alpha2Code: "GP"},
		{Name: "Guam", Alpha2Code: "GU"},
		{Name: "Guatemala", Alpha2Code: "GT"},
		{Name: "Guernsey", Alpha2Code: "GG"},
		{Name: "Guinea", Alpha2Code: "GN"},
		{Name: "Guinea-Bissau", Alpha2Code: "GW"},
		{Name: "Guyana", Alpha2Code: "GY"},
		{Name: "Haiti", Alpha2Code: "HT"},
		{Name: "Heard Island and McDonald Islands", Alpha2Code: "HM"},
		{Name: "Holy See", Alpha2Code: "VA"},
		{Name: "Honduras", Alpha2Code: "HN"},
		{Name: "Hong Kong", Alpha2Code: "HK"},
		{Name: "Hungary", Alpha2Code: "HU"},
		{Name: "Iceland", Alpha2Code: "IS"},
		{Name: "India", Alpha2Code: "IN"},
		{Name: "Indonesia", Alpha2Code: "ID"},
		{Name: "Iran (Islamic Republic of)", Alpha2Code: "IR"},
		{Name: "Iraq", Alpha2Code: "IQ"},
		{Name: "Ireland", Alpha2Code: "IE"},
		{Name: "Isle of Man", Alpha2Code: "IM"},
		{Name: "Israel", Alpha2Code: "IL"},
		{Name: "Italy", Alpha2Code: "IT"},
		{Name: "Jamaica", Alpha2Code: "JM"},
		{Name: "Japan", Alpha2Code: "JP"},
		{Name: "Jersey", Alpha2Code: "JE"},
		{Name: "Jordan", Alpha2Code: "JO"},
		{Name: "Kazakhstan", Alpha2Code: "KZ"},
		{Name: "Kenya", Alpha2Code: "KE"},
		{Name: "Kiribati", Alpha2Code: "KI"},
		{Name: "Korea (Democratic People's Republic of)", Alpha2Code: "KP"},
		{Name: "Korea (Republic of)", Alpha2Code: "KR"},
		{Name: "Kuwait", Alpha2Code: "KW"},
		{Name: "Kyrgyzstan", Alpha2Code: "KG"},
		{Name: "Lao People's Democratic Republic", Alpha2Code: "LA"},
		{Name: "Latvia", Alpha2Code: "LV"},
		{Name: "Lebanon", Alpha2Code: "LB"},
		{Name: "Lesotho", Alpha2Code: "LS"},
		{Name: "Liberia", Alpha2Code: "LR"},
		{Name: "Libya", Alpha2Code: "LY"},
		{Name: "Liechtenstein", Alpha2Code: "LI"},
		{Name: "Lithuania", Alpha2Code: "LT"},
		{Name: "Luxembourg", Alpha2Code: "LU"},
		{Name: "Macao", Alpha2Code: "MO"},
		{Name: "Macedonia (the former Yugoslav Republic of)", Alpha2Code: "MK"},
		{Name: "Madagascar", Alpha2Code: "MG"},
		{Name: "Malawi", Alpha2Code: "MW"},
		{Name: "Malaysia", Alpha2Code: "MY"},
		{Name: "Maldives", Alpha2Code: "MV"},
		{Name: "Mali", Alpha2Code: "ML"},
		{Name: "Malta", Alpha2Code: "MT"},
		{Name: "Marshall Islands", Alpha2Code: "MH"},
		{Name: "Martinique", Alpha2Code: "MQ"},
		{Name: "Mauritania", Alpha2Code: "MR"},
		{Name: "Mauritius", Alpha2Code: "MU"},
		{Name: "Mayotte", Alpha2Code: "YT"},
		{Name: "Mexico", Alpha2Code: "MX"},
		{Name: "Micronesia (Federated States of)", Alpha2Code: "FM"},
		{Name: "Moldova (Republic of)", Alpha2Code: "MD"},
		{Name: "Monaco", Alpha2Code: "MC"},
		{Name: "Mongolia", Alpha2Code: "MN"},
		{Name: "Montenegro", Alpha2Code: "ME"},
		{Name: "Montserrat", Alpha2Code: "MS"},
		{Name: "Morocco", Alpha2Code: "MA"},
		{Name: "Mozambique", Alpha2Code: "MZ"},
		{Name: "Myanmar", Alpha2Code: "MM"},
		{Name: "Namibia", Alpha2Code: "NA"},
		{Name: "Nauru", Alpha2Code: "NR"},
		{Name: "Nepal", Alpha2Code: "NP"},
		{Name: "Netherlands", Alpha2Code: "NL"},
		{Name: "New Caledonia", Alpha2Code: "NC"},
		{Name: "New Zealand", Alpha2Code: "NZ"},
		{Name: "Nicaragua", Alpha2Code: "NI"},
		{Name: "Niger", Alpha2Code: "NE"},
		{Name: "Nigeria", Alpha2Code: "NG"},
		{Name: "Niue", Alpha2Code: "NU"},
		{Name: "Norfolk Island", Alpha2Code: "NF"},
		{Name: "Northern Mariana Islands", Alpha2Code: "MP"},
		{Name: "Norway", Alpha2Code: "NO"},
		{Name: "Oman", Alpha2Code: "OM"},
		{Name: "Pakistan", Alpha2Code: "PK"},
		{Name: "Palau", Alpha2Code: "PW"},
		{Name: "Palestine, State of", Alpha2Code: "PS"},
		{Name: "Panama", Alpha2Code: "PA"},
		{Name: "Papua New Guinea", Alpha2Code: "PG"},
		{Name: "Paraguay", Alpha2Code: "PY"},
		{Name: "Peru", Alpha2Code: "PE"},
		{Name: "Philippines", Alpha2Code: "PH"},
		{Name: "Pitcairn", Alpha2Code: "PN"},
		{Name: "Poland", Alpha2Code: "PL"},
		{Name: "Portugal", Alpha2Code: "PT"},
		{Name: "Puerto Rico", Alpha2Code: "PR"},
		{Name: "Qatar", Alpha2Code: "QA"},
		{Name: "Romania", Alpha2Code: "RO"},
		{Name: "Russian Federation", Alpha2Code: "RU"},
		{Name: "Rwanda", Alpha2Code: "RW"},
		{Name: "Réunion", Alpha2Code: "RE"},
		{Name: "Saint Barthélemy", Alpha2Code: "BL"},
		{Name: "Saint Helena, Ascension and Tristan da Cunha", Alpha2Code: "SH"},
		{Name: "Saint Kitts and Nevis", Alpha2Code: "KN"},
		{Name: "Saint Lucia", Alpha2Code: "LC"},
		{Name: "Saint Martin (French part)", Alpha2Code: "MF"},
		{Name: "Saint Pierre and Miquelon", Alpha2Code: "PM"},
		{Name: "Saint Vincent and the Grenadines", Alpha2Code: "VC"},
		{Name: "Samoa", Alpha2Code: "WS"},
		{Name: "San Marino", Alpha2Code: "SM"},
		{Name: "Sao Tome and Principe", Alpha2Code: "ST"},
		{Name: "Saudi Arabia", Alpha2Code: "SA"},
		{Name: "Senegal", Alpha2Code: "SN"},
		{Name: "Serbia", Alpha2Code: "RS"},
		{Name: "Seychelles", Alpha2Code: "SC"},
		{Name: "Sierra Leone", Alpha2Code: "SL"},
		{Name: "Singapore", Alpha2Code: "SG"},
		{Name: "Sint Maarten (Dutch part)", Alpha2Code: "SX"},
		{Name: "Slovakia", Alpha2Code: "SK"},
		{Name: "Slovenia", Alpha2Code: "SI"},
		{Name: "Solomon Islands", Alpha2Code: "SB"},
		{Name: "Somalia", Alpha2Code: "SO"},
		{Name: "South Africa", Alpha2Code: "ZA"},
		{Name: "South Georgia and the South Sandwich Islands", Alpha2Code: "GS"},
		{Name: "South Sudan", Alpha2Code: "SS"},
		{Name: "Spain", Alpha2Code: "ES"},
		{Name: "Sri Lanka", Alpha2Code: "LK"},
		{Name: "Sudan", Alpha2Code: "SD"},
		{Name: "Suriname", Alpha2Code: "SR"},
		{Name: "Svalbard and Jan Mayen", Alpha2Code: "SJ"},
		{Name: "Swaziland", Alpha2Code: "SZ"},
		{Name: "Sweden", Alpha2Code: "SE"},
		{Name: "Switzerland", Alpha2Code: "CH"},
		{Name: "Syrian Arab Republic", Alpha2Code: "SY"},
		{Name: "Taiwan, Province of China", Alpha2Code: "TW"},
		{Name: "Tajikistan", Alpha2Code: "TJ"},
		{Name: "Tanzania, United Republic of", Alpha2Code: "TZ"},
		{Name: "Thailand", Alpha2Code: "TH"},
		{Name: "Timor-Leste", Alpha2Code: "TL"},
		{Name: "Togo", Alpha2Code: "TG"},
		{Name: "Tokelau", Alpha2Code: "TK"},
		{Name: "Tonga", Alpha2Code: "TO"},
		{Name: "Trinidad and Tobago", Alpha2Code: "TT"},
		{Name: "Tunisia", Alpha2Code: "TN"},
		{Name: "Turkey", Alpha2Code: "TR"},
		{Name: "Turkmenistan", Alpha2Code: "TM"},
		{Name: "Turks and Caicos Islands", Alpha2Code: "TC"},
		{Name: "Tuvalu", Alpha2Code: "TV"},
		{Name: "Uganda", Alpha2Code: "UG"},
		{Name: "Ukraine", Alpha2Code: "UA"},
		{Name: "United Arab Emirates", Alpha2Code: "AE"},
		{Name: "United Kingdom of Great Britain and Northern Ireland", Alpha2Code: "GB"},
		{Name: "United States Minor Outlying Islands", Alpha2Code: "UM"},
		{Name: "United States of America", Alpha2Code: "US"},
		{Name: "Uruguay", Alpha2Code: "UY"},
		{Name: "Uzbekistan", Alpha2Code: "UZ"},
		{Name: "Vanuatu", Alpha2Code: "VU"},
		{Name: "Venezuela (Bolivarian Republic of)", Alpha2Code: "VE"},
		{Name: "Viet Nam", Alpha2Code: "VN"},
		{Name: "Virgin Islands (British)", Alpha2Code: "VG"},
		{Name: "Virgin Islands (U.S.)", Alpha2Code: "VI"},
		{Name: "Wallis and Futuna", Alpha2Code: "WF"},
		{Name: "Western Sahara", Alpha2Code: "EH"},
		{Name: "Yemen", Alpha2Code: "YE"},
		{Name: "Zambia", Alpha2Code: "ZM"},
		{Name: "Zimbabwe", Alpha2Code: "ZW"},
	}
}
